#
# Samsung thermal specific Makefile
#
ccflags-y += -I$(srctree)/drivers/soc/samsung/include -I$(srctree)/include/soc/samsung -I$(srctree)/arch/arm/mach-exynos/include -I$(srctree)/arch/arm/plat-samsung/include
obj-$(CONFIG_EXYNOS_THERMAL)	+= exynos_tmu.o exynos_thermal.o cal_tmu.o